services:
  discovery_service:
    build:
      context: ./DiscoveryService
      dockerfile: Dockerfile
    container_name: discoveryservice
    ports:
      - "8010:8010"
    environment:
      - SPRING_APPLICATION_NAME=DiscoveryService
      - SERVER_PORT=8010
      - EUREKA_INSTANCE_HOSTNAME=discoveryservice
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://discoveryservice:8010/eureka

  appointment_handler:
    build:
      context: ./appointment_handler
      dockerfile: Dockerfile
    container_name: appointmenthandler
    ports:
      - "8090:8090"
    environment:
      - SPRING_APPLICATION_NAME=appointment-api
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_URL=jdbc:mysql://appointmentdb:3306/appointment_handler_database
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=appointmentpassword
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://discoveryservice:8010/eureka
    depends_on:
      - discovery_service
      - appointmentdb

  user_handler:
    build:
      context: ./users_handler
      dockerfile: Dockerfile
    container_name: userhandler
    ports:
      - "8091:8091"
    environment:
      - SPRING_APPLICATION_NAME=users-api
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_URL=jdbc:mysql://userdb:3306/user_handler_database
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=userpassword
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://discoveryservice:8010/eureka
    depends_on:
      - discovery_service
      - userdb

  api_gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8092:8092"
    environment:
      - SPRING_APPLICATION_NAME=gateway
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://discoveryservice:8010/eureka
    depends_on:
      - discovery_service


  appointmentdb:
    image: mysql:8.0
    container_name: appointmentdb
    environment:
      - MYSQL_ROOT_PASSWORD=appointmentpassword
      - MYSQL_DATABASE=appointment_handler_database
    ports:
      - "3306:3306"
    volumes:
      - appointmentdb_data:/var/lib/mysql

  userdb:
    image: mysql:8.0
    container_name: userdb
    environment:
      - MYSQL_ROOT_PASSWORD=userpassword
      - MYSQL_DATABASE=user_handler_database
    ports:
      - "3307:3306"
    volumes:
      - userdb_data:/var/lib/mysql

volumes:
  appointmentdb_data:
  userdb_data:


