spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: appointment-api
        uri: lb://appointment-api
        predicates:
          - Path=/appointments/**
        filters:
          - AuthenticationFilter

      - id: user-api
        uri: lb://user-api
        predicates:
          - Path=/users/**,/auth/**
        filters:
          - AuthenticationFilter

      - id: record-api
        uri: lb://record-api
        predicates:
          - Path=/records/**
        filters:
          - AuthenticationFilter

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://discoveryservice:8010/eureka/

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000
