spring:
  application:
    name: gateway

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/


cloud:
  gateway:
    routes:

    - id: appointment-api
      uri: lb://appointment-api
      predicates:
        - Path=/appointments/**
