spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: appointment-api
        uri: lb://appointment-api
        predicates:
          - Path=/appointments/**
      - id: user-api
        uri: lb://user-api
        predicates:
          - Path=/users/**
      - id: record-api
        uri: lb://record-api
        predicates:
          - Path=/records/**
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/
